### ISSUE TITLE
Change config format for ICPC contest type

### ISSUE THREAD

**Issue by MasloMaslane** [sio2project/sinol-make#132]
The config for ICPC contest type should look like this:
```yml
sinol_expected_scores:
  abc1.cpp:
    expected: {1: OK, 2: OK, 3: OK}
    status: OK
  abc2.cpp:
    expected: {1: OK, 2: TL, 3: OK}
    status: TL
```
